env:
  - COMPOSER_OPTIONS=""
  - COMPOSER_OPTIONS="--prefer-lowest"

language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install: composer update ${COMPOSER_OPTIONS}

script: bin/phpunit
